// <auto-generated />
using AppaRently.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AppaRently.Infrastructure.Migrations
{
    [DbContext(typeof(AppaRentlyDbContext))]
    [Migration("20260623235900_AddApartmentImageUrl")]
    partial class AddApartmentImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // The runtime does not use this model at migration execution time.
#pragma warning restore 612, 618
        }
    }
}
